# Generated by Django 5.2.3 on 2025-06-14 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signal_type', models.CharField(db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_reason', models.TextField(blank=True, null=True)),
                ('suggested_stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('suggested_take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('sma_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('rsi_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('macd_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('macd_signal_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('macd_histogram_value', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bollinger_upper', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bollinger_middle', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('bollinger_lower', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trade_type', models.CharField(max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading_bot.signal')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
