# Generated by Django 5.2.3 on 2025-06-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='consensus_models_agreed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='consensus_models_queried',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='raw_ai_responses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
