# Generated by Django 5.2.3 on 2025-06-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0002_signal_consensus_models_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='ai_key_indicators_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
