# Generated by Django 5.2.3 on 2025-06-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0003_signal_ai_key_indicators_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='price_at_plus_15m',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='price_at_plus_1hr',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='price_at_plus_30m',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='price_at_plus_5m',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
